## Pytorch

In [52]:
import torch
A = torch.arange(30)
A.shape # (30)
B = A.reshape([5, 3, 2])
print(B.shape)

# Concatenate
A = torch.arange(4).reshape(2, 2)
print(A)
C = torch.cat((A, A), 1)
print(C)

torch.Size([5, 3, 2])
tensor([[0, 1],
        [2, 3]])
tensor([[0, 1, 0, 1],
        [2, 3, 2, 3]])


## Einops

In [6]:
import einops

In [29]:
A = torch.arange(300)
A.shape # (300)

# Decompose
B = torch.reshape(A, (2, 150)).shape # (300) -> (2, 150)
B = einops.rearrange(A, "(num a) -> num a", num=2)
B.shape # (2, 150)
B = einops.rearrange(A, "(a b c) -> a b c", a=10, b=5)
B.shape # (10, 5, 6)

# Compose
C = einops.rearrange(B, "a b c -> a (b c)") # (10, 5, 6) -> (10, 30)
C.shape # (10, 30)

torch.Size([10, 30])

## Einsum


In [28]:
# Einsum universal formula
# z = einsum(x, y, "a b c, b c d -> a b c")
# z[a, b, c] = \sum_{d} x[a, b, c] * y[b, c, d]

A = torch.arange(6).reshape(2, 3)
B = torch.arange(6).reshape(3, 2)

# dotproduct
print(A)
print(B)
print(einops.einsum(A, B, "a b, b c -> a c"))

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[10, 13],
        [28, 40]])


## Einx

https://github.com/fferflo/einx